### ISSUE TITLE
Typos in DAQ/src/StrawRecoFromFragments_module.cc

### ISSUE THREAD

**Issue by kutschke** [Mu2e/Offline#1012]
In this file the class name has a typo everywhere the it occurs: Fragmnets, instead of Fragments.

   https://github.com/Mu2e/Offline/blob/main/DAQ/src/StrawRecoFromFragments_module.cc

Please submit a PR with just this to fix it.

**Comment by neshvig10** [comment]
fixed

**Comment by kutschke** [comment]
Resolved in PR #1017
