### ISSUE TITLE
Agree with filename recommendations

### ISSUE THREAD

**Issue by kutschke** [Mu2e/Offline#149]
I agree with Ray's recommendation that the filenames of output files ( art, root ... ) should not be differentiated mt/non-mt.

> Ray, if we remove the MT fcl files, would we then have an additional fcl layer on top of the base non-MT layer if we want to run MT?

I would leave the MT fcl files, but change the process name and output file name in the MT fcl files to be the same and nn-MT, or better, the MT fcl file becomes one to two lines, taking the names from non-MT.

_Originally posted by @rlcee in https://github.com/Mu2e/Offline/pull/145#issuecomment-592080910_

**Comment by rlcee** [comment]
There are 4 files in Offline which run MT.  All the files have "MT" in the name and include a non-MT fcl file.  There are two files in Production which follow this pattern. So for these, this pattern is one suggested above.  

Also in Production are 9 MT fcl with a different pattern where there is no non-MT fcl, there is only one fcl file, it is MT, and the fcl file name does not contain "MT".  This was apparently a different, but consistent, choice.

I don't feel strongly about having these two patterns.  Changing anything in MDC now would have fallout for active MDC campaigns. If there is no objection within a few days, I suggest we close this issue.
