### ISSUE TITLE
use of std::move ?

### ISSUE THREAD

**Issue by ryuwd** [Mu2e/Offline#255]
Some modules use `std::move` in a way that prevents copy elision (an optimisation where a function return value is created in memory outside function stack memory.)

An example from a recent run of clang-tidy in PR #254 shows examples of this in `GeometryService/src/ProductionTargetMaker.cc`.

https://gist.github.com/FNALbuild/dc7385aec847b7037c7e7dce62d3e570#file-clang-tidy-log

Although this is in the branch `Mu2eII_SM21` this code is also present in `master`.

FNALbuild now uploads logfiles to GitHub gists, including clang-tidy recommendations, meaning this output should be more accessible to everyone from now on.

**Comment by rlcee** [comment]
There are no more inappropriate "return std::move(x)" in Offline
