### ISSUE TITLE
SensitiveDetectorHelper monolith

### ISSUE THREAD

**Issue by gaponenko** [Mu2e/Offline#322]
The  SensitiveDetectorHelper class holds data structures to accumulate detector hits, which must be per-thread.   But it also contains code like registerSensitiveDetectors(), which needs to be called once per job.  The user of the latter code, Mu2eG4MTRunManager, gets all the data collections as its nested members, and  they  are not per-thread.   This is confusing and unnecessary.    It would be better to separate the data storage part from the detector registration.

**Comment by kutschke** [comment]
Do you have a concrete proposal?

**Comment by gaponenko** [comment]
Not at the moment.

**Comment by gaponenko** [comment]
Superseded by https://github.com/Mu2e/Offline/issues/690
