### ISSUE TITLE
CaloReco/fcl/prolog_trigger.fcl is overwriting module instances created by prolog.fcl

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/Offline#423]
The calo trigger prolog is using the same module instance names as the regular reco sequence, which means the behavior of Oflfine depends on the order in which they are sourced, creating unexpected and sometimes erroneous results.

**Comment by gianipez** [comment]
this issue was addressed here: https://github.com/Mu2e/Offline/pull/421
