### ISSUE TITLE
CalPatRec depends on TrkDiag

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/Offline#488]
CalPatRec, which contains modules which are run in production, depends on the TrkDiag package, and in particular on the obsolete KalDiag module.  In particular, CalPatRec/fcl/prolog.fcl #includes TrkDiag/fcl/KalDiag.fcl.  This dependence needs to be removed.

**Comment by pavel1murat** [comment]
I think that include statement can be just commented out / deleted, together with the MergePatRec-related fcl. MergePatRec is a history

**Comment by kutschke** [comment]
Who own's CalPatRec these days?  Bertrand?  Pasha?  Giani?  All of the above?

**Comment by pavel1murat** [comment]
Giani and I.

**Comment by pavel1murat** [comment]
Dave, Rob - just comment out the problematic part of the fcl as I indicated above. That wont affect anything.

**Comment by kutschke** [comment]
Please submit a pull request with the offending lines removed (not commented out).

Should we also remove MergePatRec?

**Comment by kutschke** [comment]
Pasha or Giani: I would like one of you to make a PR to resolve this.

**Comment by rlcee** [comment]
completed with #834
