### ISSUE TITLE
Calo digitization window should be explicit fcl parameters instead of blindTime and endTimeBuffer

### ISSUE THREAD

**Issue by bonventre** [Mu2e/Offline#596]
https://github.com/Mu2e/Offline/blob/6f0c8d2308718cdca1374d43e2342eaf8a988d19/CaloMC/src/CaloDigiMaker_module.cc#L178

**Comment by rlcee** [comment]
@bonventre @bechenard It looks like this was done.  May I close this?

**Comment by bonventre** [comment]
I think the issue here was specifically that the fcl parameters should be digitizationStart and digitizationEnd, instead of calculating those indirectly, so the problem is still here

**Comment by bechenard** [comment]
Yes, apologies for forgetting to do this.

Bertrand

**Comment by rlcee** [comment]
Done in #732
