### ISSUE TITLE
Calorimeter has duplicate volumes

### ISSUE THREAD

**Issue by rlcee** [Mu2e/Offline#68]
setStepLimitToAllSuchVolumes WARNING: found caloBackPlateFEELog 2 times
setStepLimitToAllSuchVolumes WARNING: found caloCrystalFrameInLog 2 times
setStepLimitToAllSuchVolumes WARNING: found caloFEEBoxInLog 2 times
setStepLimitToAllSuchVolumes WARNING: found caloFrontPlateLog 2 times
setStepLimitToAllSuchVolumes WARNING: found caloFullBackPlateLog 2 times
setStepLimitToAllSuchVolumes WARNING: found caloHoleBackLog 2 times
setStepLimitToAllSuchVolumes WARNING: found calofullCrystalDiskLog 2 times

**Comment by bechenard** [comment]
Just sent a pull request for this one

**Comment by rlcee** [comment]
fixed with PR #117, thanks!
