### ISSUE TITLE
Update mu2e_main.cc

### ISSUE THREAD

**Issue by gaponenko** [Mu2e/Offline#695]
Once we upgrade to an art version that includes this pull 
https://github.com/art-framework-suite/art/pull/122
we should modify our Mu2e/src/mu2e_main.cc accordingly.

**Comment by kutschke** [comment]
Thanks for initiating this and working with Kyle to converge on a good solution.  I will watch for the opportunity to do this.

**Comment by rlcee** [comment]
It appears this was fully resolved in #754, I will close this in one day if no one objects.
