### ISSUE TITLE
Consider removing TString::Form dependence from certain modules, e.g., Mu2eG4 and others

### ISSUE THREAD

**Issue by resnegfk** [Mu2e/Offline#709]

**Comment by rlcee** [comment]
@resnegfk I only see this being used in a few places in Mu2eG4/src/constructCRV.cc, are there others you are concerned about?  Why are you concerned?

**Comment by resnegfk** [comment]
It is an unnecessary dependence on ROOT which could be avoided by using std::ostringstream

**Comment by rlcee** [comment]
Several places where Form was used in non-root-related code are now updated.  There remains 100's of places where Form is used in root-related places, primarily histogram titles.  Since this doesn't introduce new root dependence, I've left them.  Reopen the Issue if those also need to be updated.
