### ISSUE TITLE
PrimaryProtonGun_module.cc uses duplicate seeds in MT mode

### ISSUE THREAD

**Issue by kutschke** [Mu2e/Offline#744]
EventGenerator/src/PrimaryProtonGun_module.cc is an art::ReplicatedProducer.  The issue is that all instances are seeded identically.  This needs to be fixed.

I believe that the MDC2020 POT samples are OK even though they were run with 2 threads.  The reason is that the random engine used in each G4 thread was uniquely re-seeded at the start of each event.  So there is enough downstream randomness.

This is the only replicated producer in our code base.  We should develop a solution that transfers easily to future replicated producers.

See also issue #745 - these may need a common solution.

**Comment by rlcee** [comment]
Since there is no need for this module to run multi-threaded, we will leave it as a legacy module and this issue is solved.
