### ISSUE TITLE
Add total charge to StrawDigiMC

### ISSUE THREAD

**Issue by bonventre** [Mu2e/Offline#79]
The total charge from all the ionizations for a digi should be added to StrawDigiMC for diagnostics.

**Comment by rlcee** [comment]
A relevant merge is noted, should this be closed?  If not, what needs to be added?

**Comment by bonventre** [comment]
Weird, it doesn't look like the quoted merge actually has anything to do with this, not sure how it got labelled that way. This never got implemented, but it was mostly relevant when we were debugging the cluster physics sims which is settled now, I will close this.
