### ISSUE TITLE
Consolidate duplicate blocks of code

### ISSUE THREAD

**Issue by kutschke** [Mu2e/Offline#844]
This is to whoever takes over Roberto's role as the CORSIKA expert.  There are duplicate blocks of code at:

https://github.com/Mu2e/Offline/blob/72ad4f72f5fb125135417b9d2d2b896af1a96823/Analyses/src/CORSIKAGenPlots_module.cc#L211

and
https://github.com/Mu2e/Offline/blob/72ad4f72f5fb125135417b9d2d2b896af1a96823/Analyses/src/CRYGenPlots_module.cc#L187

These should be consolidated into a class/function that is used in both places.

**Comment by rlcee** [comment]
Addressed in #848

**Comment by rlcee** [comment]
Duplicate code in `Sources/src/*Ext*` can be addressed with 
`Sources/inc/ExtMonFNALMARSUtils.hh and .cc`

**Comment by rlcee** [comment]
MARS source project completed with #853
