### ISSUE TITLE
Resolve Mu2eUtilities<->RecoDataProducts dependency loop

### ISSUE THREAD

**Issue by rlcee** [Mu2e/Offline#85]
Please move
Mu2eUtilities/inc/BuildLinearFitMatrixSums.hh
Mu2eUtilities/inc/TwoLinePCA.hh
to GeneralUtilities to prevent these references
Offline/RecoDataProducts/inc/CosmicTrack.hh:#include "Mu2eUtilities/inc/BuildLinearFitMatrixSums.hh"
Offline/RecoDataProducts/src/StereoHit.cc://#include "Mu2eUtilities/inc/TwoLinePCA.hh"
causing a dependency loop (Mu2eUtilities depends on RecoDataProducts,
so the reverse is not appropriate)

More careful review might result in a different recommended move.

**Comment by brownd1978** [comment]
These were all spurious includes.  I have updated the files to remove them.  Pull request 88

**Comment by rlcee** [comment]
fixed
