### ISSUE TITLE
CRVResponse package contains a mix of reco and MC modules

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/Offline#868]
This package should be split to separate simulation from reconstruction, and (perhaps) calibration from reconstruction.

**Comment by rlcee** [comment]
It looks like we only run two crv modules in reco: CrvRecoPulsesFinder and CrvCoincidenceClusterFinder.  I could move these two to a new directory called CRVReco.  Neither of them has any MC dependence at first glance.  @ehrlich-uva please correct me..

**Comment by ehrlich-uva** [comment]
The reco modules we are running are the CrvRecoPulseFinder and the CrvCoincidenceFinder. There is also a CrvCoincidenceClusterMatchMC that follows the CrvCoincidenceFinder. It matches the reco clusters with the MC.

The CrvCoincidenceCheck and CrvCoincidenceClusterFinder are outdated modules that shouldn't be used anymore. Perhaps we could remove them.

**Comment by rlcee** [comment]
Hmm, I was fooled by the fact that the reco instance of CrvCoincidenceFinder is called CrvCoincidenceClusterFinder.  Was this on purpose to preserve product names or is it a mistake?

I would go ahead a remove the obsolete modules, they would be easy to get back. 

May I proceed?  I will run all the usual checks.  Thanks

**Comment by ehrlich-uva** [comment]
I don't remember why I kept the name CrvCoincidenceClusterFinder in the fcl, but it's possible that I did it to preserving the product name.
Yes, you may proceed to remove the obsolete modules.
Thank you.

**Comment by rlcee** [comment]
I will close this tomorrow unless there is any objection

**Comment by rlcee** [comment]
reco modules split off to a new CRVReco directory, simulation stays in CRVResponse - issue complete
