### ISSUE TITLE
Linearizing nested std::vectors

### ISSUE THREAD

**Issue by kutschke** [Mu2e/Offline#876]
Mu2e has a number of data products with the type of ```std::vector<Digi>``` where Digi internally contains ```std::vector<some integral or floating type>```, representing a waveform.  Typically the length of the waveform varies from object to object.   Moreover,  for raw data from the experiment the number of digis and the total length of the waveforms is known (or knowable) before the data product is created.

An alternative way to represent this data is to pack everything into contiguous memory and provide the facade classes that allow end users to access it as if it were a ```std::vector<Digi>```.  The alternative representation has several advantages.

1. Fewer heap operations when creating the data product or reading it from a file.
2. If the typical access pattern is to loop over the outer vector, then the alternate implementation is likely to have fewer cache misses.
3. Streaming the object to an output file is simpler and faster because it's in contiguous memory.

Below is a message from Matti Kortelainen who is part of the Fermilab CMS Software group.  It describes class templates to implement that above.

Mu2e should consider if we want to use this technology for our data product classes that have this pattern.

> Following up the discussion in the art stakeholders meeting, here is
> one example of a data product class that linearizes nested vectors
> https://github.com/cms-sw/cmssw/blob/master/RecoTracker/TkHitPairs/interface/IntermediateHitDoublets.h
> (this specific example is transient product though)
> 
> The interface tries to emulate vector<vector<LayerPairHitDoublets>>.
> The levels of indexing are
> - Tracking region (like eta-phi cone)
> - Set (pair) of layers of the CMS pixel detector
> 
> (ok, this is a somewhat bad example, because HitDoublets class, held by
> LayerPairHitDoublets, still holds one vector, but at least the
> construct removed one layer of vectors)
> 
> 
> Here is another one, which is generic
> https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/DetSetVectorNew.h
> for which we actually have the vector<vector<T>> version available as
> well (and still in use :( ) in
> https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/DetSetVector.h
> 
> The edm::DetSetVector<T> is really vector<edm::DetSet<T>>, and
> edmNew::DetSetVector<T> internally holds vector<T> and provides an
> interface somewhat similar to edm::DetSet<T> for the nested layer.
> 
> 
> Here is another one that I crafted recently as an example for a case
> where we don't really want to guarantee long-term ability to read
> edmNew::DetSetVector<SiStripApproximateCluster>
> https://github.com/makortel/cmssw/blob/4351ec8b60bfac938423b46b1e7008f2e31d888b/DataFormats/SiStripCluster/interface/SiStripApproximateClusterCollection.h
> (it compiles, but I have not tested running it)
> 
> 
> The code is mostly complicated so not necessarily easy to digest
> (including me), but if you have questions I'll be happy to (try to)
> answer.
> 
> 
> Hope this helps,
> Matti

**Comment by rlcee** [comment]
Propose adding this text to #439 and closing this as duplicate

**Comment by kutschke** [comment]
> Propose adding this text to #439 and closing this as duplicate

Good idea.  Please go ahead.
