### ISSUE TITLE
CaloClusterFast cluster times differ dramatically from CaloClusterMaker cluster times

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/Offline#884]
The fast Calorimeter clustering module CaloClusterFast produces clusters that have times that differ by ~60ns WRT the 'same' clusters reconstructed by CaloClusterMaker.  This forces different configurations for downstream modules that in principle shouldn't care which clusters are used.  This offset should be corrected for inside CaloClusterFast, preferably using parameters coming from Conditions.

**Comment by brownd1978** [comment]
I plan to retire in 2030, so that's perfect timing!

**Comment by kutschke** [comment]
Does PR #887 close this issue?  I created a new issue for Bertrands future solution.

**Comment by brownd1978** [comment]
Addressed in PR 887
